# config: betterGame
config: originalGame
# config: debugStars
# config: debugCellars
# config: debugShadowCasting
# config: debugSky

keyMap:
  ArrowUp: "forward"
  ArrowDown: "backward"
  ArrowLeft: "turnLeft"
  ArrowRight: "turnRight"

  w: "forward"
  s: "backward"
  q: "turnLeft"
  e: "turnRight"
  a: "strafeLeft"
  d: "strafeRight"
  "?": "showInfo"
  m: "showMap"
  f: "toggleFullscreen"
  p: "togglePause"

  1: ["loadLevel", "city"]
  2: ["loadLevel", 0]

commands:
  turnLeft: ["turn", 1]
  turnRight: ["turn", -1]
  strafeLeft: ["exec", "turnLeft", "forward", "turnRight"]
  strafeRight: ["exec", "turnRight", "forward", "turnLeft"]
  welcomeMessage: ["showMessage", "Welcome to the Bard's Tale!"]

configs:
  # Full configs:
  originalGame:
    configs: ["atGuildSouth", "facingNorth", "earlyMorning", "standard"]
  betterGame:
    configs: ["originalGame", "atGuild", "facingEast"]
  debugStars:
    configs: ["night", "atCenter", "fast", "facingSouth", "fullscreen", "debug"]
  debugCellars:
    # configs: ["cellars", "night", "fullscreen", "debug"]
    # configs: ["cellars", "night", "facingEast", "debug"]
    # configs: ["cellars", "night", "facingNorth", "debug"]
    configs: ["beforeScarletBard", "noon", "facingEast", "debug"]
  debugShadowCasting:
    configs: ["atCenter", "morning", "fullscreen", "ultrafast", "debug"]
  debugSky:
    configs: ["atCenter", "noon", "fullscreen", "debug"]

  # Game time configs
  standard:
    dayLengthInMinutes: 30
  faster:
    dayLengthInMinutes: 10
  fast:
    dayLengthInMinutes: 2
  ultrafast:
    dayLengthInMinutes: 0.2

  # Game start time
  night:
    hour: 0
  earlyMorning:
    hour: 5
  morning:
    hour: 6
  noon:
    hour: 12
  evening:
    hour: 18

  # Game start position
  atGate:
    position: { x: 2, y: 15 }
    dir: 1
  atCenter:
    position: { x: 15, y: 15 }
  atGuildSouth:
    position: { x: 25, y: 14 }
  atGuild:
    position: { x: 25, y: 15 }
  nearGate:
    position: { x: 3, y: 15 }
  southQuarter:
    position: { x: 19, y: 4 }
  beforeScarletBard:
    position: { x: 27, y: 5 }
    dir: 1
  cellars:
    # position: { x: 1, y: 1 }
    position: { x: 0, y: 0 }
    level: 0

  # Game start direction
  facingNorth:
    dir: 0
  facingWest:
    dir: 1
  facingSouth:
    dir: 2
  facingEast:
    dir: 3

  # Init commands
  paused:
    initCommands:
      - "pause"
  fullscreen:
    initCommands:
      - "toggleFullscreen"
  debug:
    initCommands:
      - "doDebugStuff"
  orbitcontrols:
    initCommands:
      - "toggleFullscreen"
    orbitcontrols: true

  # This is included in every config
  defaults:
    dayLengthInMinutes: 30
    hour: 0
    level: "city"
    position: { x: 0, y: 0 }
    dir: 0
    initCommands: ["welcomeMessage"]
    orbitcontrols: false
    video: {
      enable: true,
      appId: "73c22632975c4133b8de33f67f89b84b",
      token: "00673c22632975c4133b8de33f67f89b84bIAAqCtBUxgBw6205wkgFQ6YtSRM/11pQTAEypqOAfjEYZAx+f9gAAAAAEAC0V+LrfH8QYAEAAQB7fxBg",
      exptoken: "00673c22632975c4133b8de33f67f89b84bIAAzMSCmcTOh0V0RHBrXdwUTIXikJ4VGZXCSyelBOhO13Qx+f9gAAAAAEABI+NBc9wAKYAEAAQD3AApg"
    }
