init: 
  hour: 12
  position:
    x: 19
    y: 25
  dir: 1
  initCommands: []
  orbitcontrols: false
  dayLengthInMinutes: 30

debug: ['atGuildBetter', 'earlyMorning', 'standard']
# debug: ['morning', 'atGate', 'fast']

keyMap:
  ArrowUp: ['move', -1]
  ArrowDown: ['move', +1]
  ArrowLeft: ['turn', 1]
  ArrowRight: ['turn', -1]

  w: ['move', -1]
  s: ['move', +1]
  q: ['turn', 1]
  e: ['turn', -1]
  a: ['strafe', -1]
  d: ['strafe', 1]
  '?': 'showInfo'
  m: 'showMap'
  f: 'toggleFullscreen'
  p: 'togglePause'

debugConfigs:
  standard:
    dayLengthInMinutes: 30
  faster:
    dayLengthInMinutes: 10
  fast:
    dayLengthInMinutes: 2
  ultrafast:
    dayLengthInMinutes: 0.2
  orbitcontrols:
    initCommands:
      - 'toggleFullscreen'
    orbitcontrols: true
  night:
    hour: 0
  earlyMorning:
    hour: 5
  morning:
    hour: 6
  noon:
    hour: 12
  evening:
    hour: 18
  atGate:
    position: {x: 2, y: 14}
    dir: 1
  atGuildStandard:
    position: {x: 25, y: 15}
    dir: 0
  atGuildBetter:
    position: {x: 25, y: 14}
    dir: 3
  nearGate:
    position: {x: 3, y: 14}
    dir: 0
  southQuarter:
    position: {x: 19, y: 25}
    dir: 1
  paused:
    initCommands:
      - 'pause'
  fullscreen:
    initCommands:
      - 'toggleFullscreen'
