config: betterGame
# config: originalGame
# config: debugStars
# config: debugCellars
# config: debugShadowCasting
# config: debugSky

keyMap:
  ArrowUp: "forward"
  ArrowDown: "backward"
  ArrowLeft: "turnLeft"
  ArrowRight: "turnRight"

  w: "forward"
  s: "backward"
  q: "turnLeft"
  e: "turnRight"
  a: "strafeLeft"
  d: "strafeRight"
  "?": "showInfo"
  m: "showMap"
  f: "toggleFullscreen"
  p: "togglePause"

  1: ["loadLevel", "city"]
  2: ["loadLevel", 0]

commands:
  turnLeft: ["turn", 1]
  turnRight: ["turn", -1]
  strafeLeft: ["exec", "turnLeft", "forward", "turnRight"]
  strafeRight: ["exec", "turnRight", "forward", "turnLeft"]

configs:
  # Full configs:
  originalGame:
    configs: ["atGuildSouth", "facingNorth", "earlyMorning", "standard"]
  betterGame:
    configs: ["originalGame", "atGuild", "facingEast"]
  debugStars:
    configs: ["night", "atCenter", "fast", "facingSouth", "debug"]
  debugCellars:
    # configs: ["cellars", "night", "fullscreen", "debug"]
    configs: ["cellars", "night", "facingEast"]
  debugShadowCasting:
    configs: ["atCenter", "morning", "fullscreen", "ultrafast", "debug"]
  debugSky:
    configs: ["atCenter", "noon", "fullscreen", "debug"]

  # Game time configs
  standard:
    dayLengthInMinutes: 30
  faster:
    dayLengthInMinutes: 10
  fast:
    dayLengthInMinutes: 2
  ultrafast:
    dayLengthInMinutes: 0.2

  # Game start time
  night:
    hour: 0
  earlyMorning:
    hour: 5
  morning:
    hour: 6
  noon:
    hour: 12
  evening:
    hour: 18

  # Game start position
  atGate:
    position: { x: 2, y: 14 }
    dir: 1
  atCenter:
    position: { x: 15, y: 14 }
  atGuildSouth:
    position: { x: 25, y: 15 }
  atGuild:
    position: { x: 25, y: 14 }
  nearGate:
    position: { x: 3, y: 14 }
  southQuarter:
    position: { x: 19, y: 25 }
    dir: 1
  cellars:
    position: { x: 1, y: 1 }
    level: 0

  # Game start direction
  facingNorth:
    dir: 0
  facingWest:
    dir: 1
  facingSouth:
    dir: 2
  facingEast:
    dir: 3

  # Init commands
  paused:
    initCommands:
      - "pause"
  fullscreen:
    initCommands:
      - "toggleFullscreen"
  debug:
    initCommands:
      - "doDebugStuff"
  orbitcontrols:
    initCommands:
      - "toggleFullscreen"
    orbitcontrols: true

  # This is included in every config
  defaults:
    dayLengthInMinutes: 30
    hour: 0
    level: "city"
    position: { x: 0, y: 0 }
    dir: 0
    initCommands: []
    orbitcontrols: false
