# config: betterGame
# config: originalGame
# config: debugStars
config: debugCellars
# config: debugShadowCasting

keyMap:
  ArrowUp: ["move", -1]
  ArrowDown: ["move", +1]
  ArrowLeft: ["turn", 1]
  ArrowRight: ["turn", -1]

  w: ["move", -1]
  s: ["move", +1]
  q: ["turn", 1]
  e: ["turn", -1]
  a: ["strafe", -1]
  d: ["strafe", 1]
  "?": "showInfo"
  m: "showMap"
  f: "toggleFullscreen"
  p: "togglePause"

configs:
  # Full configs:
  originalGame:
    configs: ["atGuildSouth", "facingNorth", "earlyMorning", "standard"]
  betterGame:
    configs: ["originalGame", "atGuild", "facingEast"]
  debugStars:
    configs: ["night", "atCenter", "fast", "facingSouth", "debug"]
  debugCellars:
    configs: ["cellars", "night", "fullscreen", "doDebugStuff", "debug"]
  debugShadowCasting:
    configs: ["atCenter", "morning", "fullscreen", "ultrafast", "debug"]

  # Game time configs
  standard:
    dayLengthInMinutes: 30
  faster:
    dayLengthInMinutes: 10
  fast:
    dayLengthInMinutes: 2
  ultrafast:
    dayLengthInMinutes: 0.2

  # Game start time
  night:
    hour: 0
  earlyMorning:
    hour: 5
  morning:
    hour: 6
  noon:
    hour: 12
  evening:
    hour: 18

  # Game start position
  atGate:
    position: { x: 2, y: 14 }
    dir: 1
  atCenter:
    position: { x: 15, y: 14 }
  atGuildSouth:
    position: { x: 25, y: 15 }
  atGuild:
    position: { x: 25, y: 14 }
  nearGate:
    position: { x: 3, y: 14 }
  southQuarter:
    position: { x: 19, y: 25 }
    dir: 1
  cellars:
    level: 0

  # Game start direction
  facingNorth:
    dir: 0
  facingWest:
    dir: 1
  facingSouth:
    dir: 2
  facingEast:
    dir: 3

  # Init commands
  paused:
    initCommands:
      - "pause"
  fullscreen:
    initCommands:
      - "toggleFullscreen"
  debug:
    initCommands:
      - "doDebugStuff"
  orbitcontrols:
    initCommands:
      - "toggleFullscreen"
    orbitcontrols: true

  # This is included in every config
  defaults:
    dayLengthInMinutes: 30
    hour: 0
    level: "city"
    position: { x: 0, y: 0 }
    dir: 0
    initCommands: []
    orbitcontrols: false
