programs:
  notImplemented:
    - ["showMessage", "Feature not implemented yet."]
    - ["delay", 0.5]
    - ["subprogram", ":arg1:"]

  emptyHouse:
    - ["overlayImage", "inside/empty"]
    - ["location", "Empty Building"]
    - ["showMessage", "You are in an empty building."]
    - ["waitForKeyPress", "(EXIT)"]
    - ["returnToCity"]

  stables:
    - ["overlayImage", "inside/empty"]
    - ["location", "Stables"]
    - [
        "showMessage",
        "Sorry, friends, all the horses have been eaten by creatures!.",
      ]
    - ["waitForKeyPress", "(EXIT)"]
    - ["returnToCity"]

  cityGate:
    - ["overlayImage", "city/city_gate"]
    - ["location", "City Gate"]
    - [
        "showMessage",
        "You stand before the city gates, which are blocked by a gigantic snow drift.",
      ]
    - ["delay", 0.3]
    - ["waitForKeyPress", "(EXIT)"]
    - ["returnToCity"]

  credits:
    - ["overlayImage", "inside/credits"]
    - ["location", "Bard's Tale"]
    - [
      "showMessage",
      "THE BARD'S TALE|Amiga was from an original design by Michael Cranford.||It was created at Interplay Productions, in Irvine, California."
      ]
    - ["waitForKeyPress"]
    - [
      "showMessage",
      "Interplay wishes to express its gratitude to a number of people who worked on|THE BARD'S TALE:||Todd Camasta|(Artwork)||Troy P. Worrell|(Programming)"
      ]
    - ["waitForKeyPress"]
    - [
      "showMessage",
      "Dave Warhol|Aarn Abbey|(Music)||Brian Fargo|(Dungeons)||Joe Ybarra|(Producer)"
      ]
    - ["waitForKeyPress", "(CONTINUE)"]
    - ["returnToCity"]


  guild:
    - ["overlayImage", "inside/guild"]
    - ["location", "The guild"]
    - [
        "selection",
        "Thou art in the guild of adventurers",
        ["Add member", "a", ["subprogram", "notImplemented", "guild"]],
        ["Remove member", "r", ["subprogram", "notImplemented", "guild"]],
        ["Create a member", "c", ["subprogram", "notImplemented", "guild"]],
        ["Delete a member", "d", ["subprogram", "notImplemented", "guild"]],
        ["Save party", "s", ["subprogram", "notImplemented", "guild"]],
        ["Leave game", "l", ["subprogram", "notImplemented", "guild"]],
        ["Enter the city", "e", "returnToCity"],
      ]

  reviewBoard:
    - ["overlayImage", "inside/review"]
    - ["location", "Review board"]
    - [
        "selection",
        "Wouldst thou like to be reviewed for",
        ["Advancement", "a", ["subprogram", "notImplemented", "reviewBoard"]],
        ["Spell Acquiring", "s", ["subprogram", "notImplemented", "reviewBoard"]],
        ["Class Change", "c", ["subprogram", "notImplemented", "reviewBoard"]],
        ["(EXIT)", "e", "returnToCity", -1],
      ]

  roscoes:
    - ["overlayImage", "inside/roscoes"]
    - ["location", "Roscoe's"]
    - ["showMessage", "Welcome, my friends, to Roscoe's Energy Emporium.|Who needeth spell points restored?"]
# has some definite spell point problems. It will cost
# Roscoe re-energizes him.
    - ["waitForKeyPress", "(EXIT)"]
    - ["returnToCity"]

  shop:
    - ["condition", "night",
       [["showMessage", "The shoppe is closed at night."], "returnToCity"], []
      ]
    - ["overlayImage", "inside/shop"]
    - ["location", "The Shoppe"]
    - ["showMessage", "Welcome to Garth's Equipment Shoppe, oh wealthy travellers!|Which of you is interested in my fine wares?"]
    - ["delay", 0.3]
    - ["waitForKeyPress", "(EXIT)"]
    - ["returnToCity"]

  scarletBard:
    - ["overlayImage", "inside/pub"]
    - ["location", "Scarlet Bard"]
    - [
        "selection",
        "Hail, travelers! Step to the bar and I'll draw you a tankard.|You can:",
        ["Order a drink", "o", ["teleport", 0, 0, 0]],
        ["Talk to barkeep", "t", ["subprogram", "notImplemented", "scarletBard"]],
        ["(EXIT)", "e", "returnToCity", -1],
      ]

  madgodTemple:
    - ["overlayImage", "inside/temple"]
    - ["location", "Mad God"]
    - [
        "selection",
        "This is the temple of the Mad God. What is thy business, unbeliever?",
        ["Speak to priest", "s", ["subprogram", "madgodSpeak"]],
        ["(EXIT)", "e", "returnToCity", -1]
      ]


  madgodSpeak:
    - ["riddle", "Only those who know the name of the Mad one are welcome.|What wilt thou say?|",
        "TARJAN",
        ["subprogram", "madgodEnter"],
        ["subprogram", "madgodWrongAnswer"],
      ]
    - ["subprogram", "madgodEnter"]

  madgodEnter:
    - ["showMessage", '"Speak not the name of the High One so loudly, lest he awaken." the priest says. "enter the catacombs, believer."']
    - ["waitForKeyPress"]
    - ["teleport", 4, 0, 0]

  madgodWrongAnswer:
    - ["showMessage", '"Quit thy babbling," the priest says.']
    - ["delay", 1.0]
    - ["subprogram", "madgodTemple"]

  harkynsCastle:
    - ["overlayImage", "inside/castle"]
    - ["location", "Castle"]
    - [
        "selection",
        "This is the entry chamber to Harkyn's Castle. It is not guarded, but a sign threatens trespassers with death.|You can:",
        ["Take stairs up", "t", ["teleport", 7, 0, 0]],
        ["(EXIT)", "e", "returnToCity", -1],
      ]

  kylearansTower:
    - [ "overlayImage", "inside/stairs" ]
    - [ "location", "Amber Tower" ]
    - [
        "selection",
        "This is the entry chamber to Kylearan's Amber Tower. A stairwell leads up to a lofty level of chambers.|You can:",
        [ "Take stairs up", "t", [ "teleport", 10, 0, 0 ] ],
        [ "(EXIT)", "e", "returnToCity", -1 ],
      ]

  mangarsTower:
    - ["overlayImage", "inside/stairs"]
    - ["location", "The Tower"]
    - [
        "selection",
        "This is the entry chamber to Mangar's Tower. A stairwell leads up to the first level of traps and terrors.|You can:",
        [ "Take stairs up", "t", [ "teleport", 11, 0, 0 ] ],
        [ "(EXIT)", "e", "returnToCity", -1 ],
      ]

  stairsDown:
    - [
      "selection",
      "There are stairs here, going down. Do you wish to take them?",
      ["Yes", "y", ["stairsDown"]],
      ["No", "n", []]
    ]

  stairsUp:
    - [
      "selection",
      "There are stairs here, going up. Do you wish to take them?",
      ["Yes", "y", ["stairsUp"]],
      ["No", "n", []]
    ]

  # stairsUp, portalUp, portalDown
  # pub
  # temple
