programs:
  emptyHouse:
    - ["overlayImage", "inside/empty"]
    - ["location", "Empty Building"]
    - ["showMessage", "You are in an empty building."]
    - ["waitForKeyPress", "(EXIT)"]
    - ["returnToCity"]

  stables:
    - ["overlayImage", "inside/empty"]
    - ["location", "Empty Building"]
    - [
        "showMessage",
        "Sorry, friends, all the horses have been eaten by creatures!.",
      ]
    - ["showMessage", "You are in an empty building."]
    - ["waitForKeyPress", "(EXIT)"]
    - ["returnToCity"]

  cityGate:
    - ["overlayImage", "city/city_gate"]
    - ["location", "City Gate"]
    - [
        "showMessage",
        "You stand before the city gates, which are blocked by a gigantic snow drift.",
      ]
    - ["waitForKeyPress", "(EXIT)"]
    - ["returnToCity"]

  credits:
    - ["overlayImage", "inside/credits"]
    - ["location", "Bard's Tale"]
    - [
        "showMessage",
        "THE BARD'S TALE IBM was from an original design by Michael Cranford.\nIt was created at Interplay Productions, in Newport Beach, California.\nInterplay wishes to express its gratitude to a number of people who worked on THE BARD'S TALE:\nTodd Camasta\n(Artwork)\nTroy P. Worrell\n(Programming)\nDave Warhol\nAarn Abbey\n(Music)\nBrian Fargo\n(Dungeons)\nJoe Ybarra\n(Producer)\n",
      ]
    - ["returnToCity"]

  guild:
    - ["overlayImage", "inside/guild"]
    - ["location", "The guild"]
    - ["returnToCity"]

  reviewBoard:
    - ["overlayImage", "inside/review"]
    - ["location", "Review board"]
    - ["returnToCity"]

  roscoes:
    - ["overlayImage", "inside/roscoes"]
    - ["location", "Roscoe's"]
    - ["showMessage", "Welcome, my friends, to Roscoe's Energy Emporium. Who needeth spell points restored?"]
# has some definite spell point problems. It will cost
# Roscoe re-energizes him.
    - ["returnToCity"]

  shop:
    - ["condition", "night",
       [["showMessage", "The shoppe is closed at night."], "returnToCity"], []
      ]
    - ["overlayImage", "inside/shop"]
    - ["location", "The Shoppe"]
    - ["showMessage", "  Welcome to Garth's Equipment Shoppe, oh wealthy travellers!\nWhich of you is interested in my fine wares?"]
    - ["returnToCity"]

  scarletBard:
    - ["overlayImage", "inside/pub"]
    - ["location", "Scarlet Bard"]
    - [
        "showMessage",
        "Hail, travelers! Step to the bar and I'll draw you a tankard.\nYou can:\nOrder a drink\nTalk to barkeep",
      ]
    - ["teleport", 0, 0, 0]

  mdTest:
    - ["overlayImage", ":arg1:"]
    - ["overlayImage", ":arg2:"]


  madgodTemple:
    - ["overlayImage", "inside/pub"]
    - ["delay", 3]
    - ["overlayImage", "inside/temple"]
    - ["location", "Mad God"]
    - [
        "selection",
        "This is the temple of the Mad God. What is thy business, unbeliever?",
        ["Speak to priest", "s", ["subprogram", "madgodSpeak"]],
        ["(EXIT)", "e", "returnToCity"]
      ]
    - ["subprogram", "madgodEnter"]


  madgodSpeak:
    - ["riddle", "Only those who know the name of the Mad one are welcome.\nWhat wilt thou say?",
        "TARJAN",
        ["subprogram", "madgodEnter"],
        ["subprogram", "madgodWrongAnswer"],
      ]

  madgodEnter:
    - ["showMessage", '"Speak not the name of the High One so loudly, lest he awaken." the priest says. "enter the catacombs, believer."']
    - ["waitForKeyPress"]
    - ["teleport", 4, 0, 0]

  madgodWrongAnswer:
    - ["showMessage", '"Quit thy babbling," the priest says.']
    - ["waitForKeyPress", "(EXIT)"]
    - ["returnToCity"]

  harkynsCastle:
    - ["overlayImage", "inside/castle"]
    - ["location", "Castle"]
    - [
        "showMessage",
        "This is the entry chamber to Harkyn's Castle. It is not guarded, but a sign threatens trespassers with death. You can:\nTake stairs up",
      ]
    - ["teleport", 7, 0, 0]

  kylearansTower:
    - ["overlayImage", "inside/stairs"]
    - ["location", "Amber Tower"]
    - [
        "showMessage",
        "This is the entry chamber to Kylearan's Amber Tower. A stairwell leads up to a lofty level of chambers. You can:\nTake stairs",
      ]
    - ["teleport", 10, 0, 0]

  mangarsTower:
    - ["overlayImage", "inside/stairs"]
    - ["location", "The Tower"]
    - [
        "showMessage",
        "This is the entry chamber to Mangar's Tower. A stairwell leads up to the first level of traps and terrors. You can:\nTake stairs",
      ]
    - ["teleport", 11, 0, 0]

  stairsDown:
    - [
      "selection",
      "There are stairs here, going down. Do you wish to take them?",
      ["Yes", "y", ["stairsDown"]],
      ["No", "n", []]
    ]

  stairsUp:
    - [
      "selection",
      "There are stairs here, going up. Do you wish to take them?",
      ["Yes", "y", ["stairsUp"]],
      ["No", "n", []]
    ]

  # stairsUp, portalUp, portalDown
  # pub
  # temple
